In [ ]:
import pandas as pd
import numpy as np

LABELS = ['label_1', 'label_2', 'label_3', 'label_4']
FEATURES = ['feature_'+ str(i) for i in range(1,257)]

In [ ]:
train = pd.read_csv("drive/MyDrive/Colab Notebooks/Lab 1/train.csv")
valid = pd.read_csv("drive/MyDrive/Colab Notebooks/Lab 1/valid.csv")
test = pd.read_csv("drive/MyDrive/Colab Notebooks/Lab 1/test.csv")

In [ ]:
print(LABELS)
print(FEATURES)

['label_1', 'label_2', 'label_3', 'label_4']
['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19', 'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24', 'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29', 'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39', 'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44', 'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49', 'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_54', 'feature_55', 'feature_56', 'feature_57', 'feature_58', 'feature_59', 'feature_60', 'feature_61', 'feature_62', 'feature_63', 'feature_64', 'feature_65', 'feature_66', 'feature_67', 'feature_68', 'feature_69

In [ ]:
print(train.shape)
train.describe()

(28520, 260)


feature_1     feature_2     feature_3     feature_4     feature_5  \
count  28520.000000  28520.000000  28520.000000  28520.000000  28520.000000   
mean      -0.225478     -0.616421     -0.212878      0.336330      0.105467   
std        0.990632      1.005573      1.075468      1.248919      0.831132   
min       -4.023911     -5.582544     -4.679888     -4.284380     -3.010300   
25%       -0.869656     -1.287018     -0.913419     -0.478661     -0.437171   
50%       -0.190790     -0.609782     -0.218800      0.295881      0.117310   
75%        0.457509      0.063174      0.490262      1.119242      0.657941   
max        4.322171      3.876604      4.267163      5.828656      3.884939   

          feature_6     feature_7     feature_8     feature_9    feature_10  \
count  28520.000000  28520.000000  28520.000000  28520.000000  28520.000000   
mean      -0.339634     -0.201756      0.742262      0.942325     -1.957584   
std        1.073267      0.943505      1.055721      0.940459      0.876939   
min       -5.034355     -4.355222     -3.806574     -2.922614     -5.203347   
25%       -1.075753     -0.823699      0.064072      0.298269     -2.556436   
50%       -0.329571     -0.193263      0.755193      0.940786     -1.949847   
75%        0.393339      0.417146      1.461846      1.579200     -1.345999   
max        3.890622      3.799406      4.817545      4.615069      1.147192   

       ...   feature_251   feature_252   feature_253   feature_254  \
count  ...  28520.000000  28520.000000  28520.000000  28520.000000   
mean   ...     -0.028098      0.296340      1.724439     -1.476765   
std    ...      0.989497      1.173378      0.968611      1.032811   
min    ...     -3.679602     -3.905801     -3.301683     -5.490267   
25%    ...     -0.692262     -0.550897      1.121631     -2.130906   
50%    ...     -0.018218      0.295523      1.783432     -1.449978   
75%    ...      0.644112      1.128566      2.383575     -0.799414   
max    ...      3.915582      4.458014      5.261775      2.861117   

        feature_255   feature_256       label_1       label_2       label_3  \
count  28520.000000  28520.000000  28520.000000  28040.000000  28520.000000   
mean       0.687445     -1.563062     30.498843     27.975107      0.799299   
std        1.028328      1.243758     17.328389      5.735913      0.400532   
min       -3.810144     -6.056032      1.000000     22.000000      0.000000   
25%       -0.008394     -2.404028     15.000000     25.000000      1.000000   
50%        0.639575     -1.650610     30.000000     27.000000      1.000000   
75%        1.347263     -0.805710     46.000000     30.000000      1.000000   
max        5.531152      3.338544     60.000000     61.000000      1.000000   

            label_4  
count  28520.000000  
mean       5.997125  
std        2.375567  
min        0.000000  
25%        6.000000  
50%        6.000000  
75%        6.000000  
max       13.000000  

[8 rows x 260 columns]

In [ ]:
print(valid.shape)
valid.describe()

(750, 260)


feature_1   feature_2   feature_3   feature_4   feature_5   feature_6  \
count  750.000000  750.000000  750.000000  750.000000  750.000000  750.000000   
mean    -0.215982   -0.623504   -0.291264    0.377151    0.178972   -0.252002   
std      0.956326    1.035303    1.128986    1.244136    0.843049    1.069149   
min     -3.600761   -5.998218   -3.933543   -3.788818   -2.352740   -4.067048   
25%     -0.834711   -1.307291   -0.998405   -0.422144   -0.424725   -0.992993   
50%     -0.205673   -0.607260   -0.307802    0.326517    0.190352   -0.196757   
75%      0.417797    0.030387    0.412266    1.156195    0.757207    0.476947   
max      2.302163    2.441009    3.116088    4.058463    2.861698    2.790602   

        feature_7   feature_8   feature_9  feature_10  ...  feature_251  \
count  750.000000  750.000000  750.000000  750.000000  ...   750.000000   
mean    -0.228841    0.771239    0.922442   -1.959988  ...    -0.051848   
std      0.955363    1.074252    0.947518    0.868173  ...     0.987202   
min     -3.307670   -3.230605   -2.501911   -4.732800  ...    -2.942192   
25%     -0.916115    0.110733    0.323182   -2.508483  ...    -0.716455   
50%     -0.212617    0.816087    0.910706   -1.918432  ...    -0.031057   
75%      0.429078    1.482462    1.535642   -1.396017  ...     0.617642   
max      3.414155    4.249192    3.708912    0.418425  ...     3.356440   

       feature_252  feature_253  feature_254  feature_255  feature_256  \
count   750.000000   750.000000   750.000000   750.000000   750.000000   
mean      0.342457     1.691002    -1.485593     0.691309    -1.567317   
std       1.141813     0.938246     1.051536     1.004137     1.268333   
min      -2.858132    -1.695706    -4.781263    -2.499728    -5.805717   
25%      -0.491588     1.049466    -2.149493     0.035928    -2.459352   
50%       0.333020     1.772243    -1.503996     0.620206    -1.634017   
75%       1.135099     2.372264    -0.847414     1.324276    -0.752141   
max       3.532709     3.927659     2.039558     4.018772     2.496667   

          label_1     label_2     label_3     label_4  
count  750.000000  736.000000  750.000000  750.000000  
mean    30.085333   28.330163    0.810667    6.117333  
std     17.489060    6.518500    0.392035    2.227895  
min      1.000000   22.000000    0.000000    0.000000  
25%     15.000000   25.000000    1.000000    6.000000  
50%     29.000000   27.000000    1.000000    6.000000  
75%     45.000000   30.000000    1.000000    6.000000  
max     60.000000   61.000000    1.000000   13.000000  

[8 rows x 260 columns]

In [ ]:
print(test.shape)
test.describe()

(750, 260)


feature_1   feature_2   feature_3   feature_4   feature_5   feature_6  \
count  750.000000  750.000000  750.000000  750.000000  750.000000  750.000000   
mean    -0.248243   -0.585421   -0.261300    0.292129    0.106505   -0.327901   
std      1.007230    1.031605    1.088193    1.275657    0.820163    1.055800   
min     -3.338338   -5.240058   -3.552587   -3.875104   -2.599635   -3.934916   
25%     -0.889425   -1.284925   -1.045593   -0.595757   -0.447941   -1.082658   
50%     -0.219966   -0.558214   -0.228610    0.242556    0.114963   -0.293032   
75%      0.432476    0.144174    0.433977    1.086600    0.621324    0.401023   
max      2.788072    2.412955    3.071344    4.845111    3.024339    2.596057   

        feature_7   feature_8   feature_9  feature_10  ...  feature_251  \
count  750.000000  750.000000  750.000000  750.000000  ...   750.000000   
mean    -0.186109    0.746488    0.896069   -1.999506  ...     0.064154   
std      0.937663    1.038833    0.912043    0.865403  ...     0.978063   
min     -2.964872   -2.428432   -2.603179   -4.547704  ...    -3.547722   
25%     -0.789457    0.097839    0.294905   -2.604528  ...    -0.563641   
50%     -0.200180    0.743686    0.903759   -2.022947  ...     0.036205   
75%      0.429726    1.483986    1.515494   -1.431881  ...     0.742721   
max      3.295141    4.404866    3.434419    0.694695  ...     3.257086   

       feature_252  feature_253  feature_254  feature_255  feature_256  \
count   750.000000   750.000000   750.000000   750.000000   750.000000   
mean      0.279551     1.792623    -1.468001     0.617542    -1.543454   
std       1.150581     0.962225     1.002188     0.999210     1.202299   
min      -3.188699    -1.288992    -4.936862    -2.188391    -5.697614   
25%      -0.552616     1.203707    -2.110703    -0.072770    -2.341033   
50%       0.250225     1.887835    -1.454391     0.549354    -1.593112   
75%       1.074692     2.446600    -0.809374     1.284066    -0.785415   
max       3.445455     4.506212     1.633000     4.192348     2.523189   

       label_1  label_2  label_3  label_4  
count      0.0      0.0      0.0      0.0  
mean       NaN      NaN      NaN      NaN  
std        NaN      NaN      NaN      NaN  
min        NaN      NaN      NaN      NaN  
25%        NaN      NaN      NaN      NaN  
50%        NaN      NaN      NaN      NaN  
75%        NaN      NaN      NaN      NaN  
max        NaN      NaN      NaN      NaN  

[8 rows x 260 columns]

Preprocessing the data

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28520 entries, 0 to 28519
Columns: 260 entries, feature_1 to label_4
dtypes: float64(257), int64(3)
memory usage: 56.6 MB


Label 2 has some empty values. These will be neglected when scaling using the standard scaler

In [ ]:
train[train['label_2'].notna()].shape

(28040, 260)

In [ ]:
from sklearn.preprocessing import StandardScaler

tr_df = train[train['label_2'].notna()]
vl_df = valid[valid['label_2'].notna()]
tst_df = test

scaler = StandardScaler()

X_train = pd.DataFrame(scaler.fit_transform(tr_df.drop(LABELS, axis = 1)), columns = FEATURES)
Y_train = tr_df['label_2']
X_valid = pd.DataFrame(scaler.transform(vl_df.drop(LABELS, axis = 1)), columns = FEATURES)
Y_valid = vl_df['label_2']

X_test = pd.DataFrame(scaler.transform(tst_df.drop(LABELS, axis = 1)), columns = FEATURES)


In [ ]:
X_train

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0      -1.940013  -1.228302  -0.165525   0.229968   0.716160   0.125273   
1      -0.185445  -0.220963   0.918071   1.102726   0.673469   0.907565   
2      -1.441485  -0.659800   0.361286   0.883175   0.182315  -0.512557   
3       0.030090  -1.824604   0.718243  -0.282762   0.841051   0.020714   
4      -0.293572  -0.166215  -1.167232   0.407595   0.298617   0.573667   
...          ...        ...        ...        ...        ...        ...   
28035   0.089590   1.603333  -0.191022   0.010724   3.493046  -0.077442   
28036   1.667679  -0.713063   0.072135  -0.032733   0.383269  -0.352452   
28037   1.374299  -0.018318   0.156473   0.388302   1.421557   0.302375   
28038  -0.784521  -0.007171   0.017062  -0.813106   1.185284  -0.790939   
28039   1.058788  -0.273280   0.605237  -0.578308   1.281187  -0.607972   

       feature_7  feature_8  feature_9  feature_10  ...  feature_247  \
0      -0.535274   2.153355  -0.491390    1.283665  ...     0.495295   
1       0.491768   0.618058  -0.156017   -0.562341  ...    -1.254022   
2       0.159565  -0.131035  -0.595500    0.843607  ...     0.808919   
3       1.067337   0.713154  -1.696776    1.329928  ...    -0.614335   
4      -1.560398   0.827008   0.069052   -0.245358  ...    -0.426291   
...          ...        ...        ...         ...  ...          ...   
28035  -1.274332   0.232200   1.638245    0.779005  ...     0.901493   
28036   1.008559  -2.154872  -0.168950    0.130621  ...     0.916408   
28037   0.320359  -0.056055   0.311155    0.868704  ...     0.438713   
28038   0.179614  -1.146858   0.297686   -1.003522  ...     0.619378   
28039   0.799522   1.223672  -1.384624    2.139506  ...     0.087246   

       feature_248  feature_249  feature_250  feature_251  feature_252  \
0        -0.692819    -0.062072     0.828025    -0.589055     2.131857   
1         0.152116    -0.894160    -0.123653     1.266511     0.398965   
2         0.524407     0.987461     0.778132     0.289806     0.722729   
3        -0.101294    -0.005114     0.366115     1.115272    -1.280607   
4        -1.224159     1.309741     1.039716    -0.814195     0.856210   
...            ...          ...          ...          ...          ...   
28035    -0.193083    -0.660340     1.725819     0.765832    -1.114043   
28036    -0.566686    -0.010798     1.217333    -0.174333     0.055826   
28037    -0.223062    -0.478127    -1.309341     1.148634    -2.010148   
28038     0.441781     0.901223     0.320610     0.729631    -0.624413   
28039    -0.096583    -1.716791    -0.552322     1.315239    -1.166240   

       feature_253  feature_254  feature_255  feature_256  
0        -0.702011    -1.312623     0.211070     0.218696  
1         0.121558     0.323067    -0.809528    -0.344385  
2         0.100518    -0.564969    -0.739008    -0.524548  
3         1.136795    -0.456450    -0.468298    -0.684481  
4         0.793276    -0.213338    -0.123390     0.475624  
...            ...          ...          ...          ...  
28035    -0.881238     1.211392     0.701167     0.501598  
28036    -0.142738    -0.369710     1.138784    -0.428881  
28037     1.063280     1.821220    -0.332335    -0.331436  
28038     0.166017    -0.201668    -1.415257    -0.162355  
28039     1.443377     1.643582    -0.082101    -1.667725  

[28040 rows x 256 columns]

In [ ]:
Y_train

480      25.0
481      25.0
482      25.0
483      25.0
484      25.0
         ... 
28515    29.0
28516    29.0
28517    29.0
28518    29.0
28519    29.0
Name: label_2, Length: 28040, dtype: float64

In [ ]:
X_valid

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0     0.050123  -1.878628   0.126923   0.587851   0.881923   0.162904   
1    -0.466270  -1.042334   1.872532   0.458924   0.726750   1.102452   
2    -1.433238   1.067748   0.781064   0.741824  -0.027139  -0.774589   
3    -0.752600   0.396091  -0.399736   0.128155   0.501778   0.490110   
4    -0.367423  -1.318577  -0.430401   1.097436   0.981841   1.078442   
..         ...        ...        ...        ...        ...        ...   
731   0.365257   0.555853  -1.854516   1.761337   0.566734   0.567394   
732   0.346081  -0.380485  -0.029704  -1.327972  -0.415881   0.057870   
733   0.135184   0.397989  -1.764658   1.627785   0.244652   0.517123   
734   0.543235   0.741378  -0.730788   0.947759   1.570852  -0.109086   
735  -1.272621  -1.725870   0.576804  -0.724203   0.066960  -1.588766   

     feature_7  feature_8  feature_9  feature_10  ...  feature_247  \
0    -0.360695   0.453246   0.488679    1.116082  ...    -0.667433   
1     0.255273   0.438065  -0.471167    0.061900  ...    -2.251340   
2     0.804213   0.204729  -0.954404    1.175598  ...     1.183243   
3     0.380701  -0.012755  -1.098645   -0.404746  ...     0.353948   
4    -0.198579   0.805612  -1.317044    0.214404  ...     0.525294   
..         ...        ...        ...         ...  ...          ...   
731   0.205268  -1.568206  -0.470678    0.843627  ...     0.276015   
732  -0.020076  -0.564833   0.552802   -0.540584  ...     0.073580   
733   1.426410  -0.643678  -1.291663    0.813495  ...     0.833547   
734   1.297605   0.155279   1.371094    0.287799  ...     0.885360   
735   0.356820  -1.586748   0.648342   -0.126118  ...    -0.488424   

     feature_248  feature_249  feature_250  feature_251  feature_252  \
0       0.101467    -0.187506     1.403447    -1.001715    -0.095823   
1       0.233567    -0.385253     0.243674     1.712794     0.021735   
2       0.680810     1.233936     1.127051    -0.522123    -0.038426   
3       0.588933     1.058106     1.283034    -0.283848    -0.627344   
4       0.251841     1.254822     0.334831     0.775507    -0.674521   
..           ...          ...          ...          ...          ...   
731     1.823348    -0.278542    -0.251511    -1.005830     0.238890   
732     0.050413     0.441214     1.628334    -1.388983     0.533158   
733     1.059859    -0.128189     0.325625     0.185163     0.486214   
734     0.034228    -0.598417    -0.417926     0.814584    -1.618312   
735     0.665253     0.940994     0.783070     0.438115     0.041544   

     feature_253  feature_254  feature_255  feature_256  
0      -1.356515    -0.236852    -1.473790    -0.382849  
1      -0.339696    -0.074751    -1.880493    -0.302714  
2       0.174983    -0.893622    -1.318243    -1.112809  
3      -0.249513    -0.299660    -0.590972    -0.685417  
4       0.827654    -0.225864     0.582602    -0.455377  
..           ...          ...          ...          ...  
731     0.861499     1.211898     1.343092     0.388070  
732    -0.577923    -2.350551     0.422800     1.653936  
733     0.531472     0.018738     0.378559     0.103179  
734     0.477750     1.471400     0.741475    -1.111189  
735    -0.468795    -1.062777    -0.884517     0.915396  

[736 rows x 256 columns]

In [ ]:
Y_valid

14     25.0
15     25.0
16     25.0
17     25.0
18     25.0
       ... 
745    29.0
746    29.0
747    29.0
748    29.0
749    29.0
Name: label_2, Length: 736, dtype: float64

In [ ]:
X_train.describe()

feature_1     feature_2     feature_3     feature_4     feature_5  \
count  2.804000e+04  2.804000e+04  2.804000e+04  2.804000e+04  2.804000e+04   
mean  -3.547646e-17  3.446284e-17  2.432671e-17  1.013613e-17  8.108904e-18   
std    1.000018e+00  1.000018e+00  1.000018e+00  1.000018e+00  1.000018e+00   
min   -3.857388e+00 -4.933583e+00 -4.145939e+00 -3.784002e+00 -3.757613e+00   
25%   -6.488065e-01 -6.667053e-01 -6.514642e-01 -6.545997e-01 -6.526620e-01   
50%    3.423282e-02  5.818910e-03 -5.231164e-03 -1.802937e-02  1.414817e-02   
75%    6.868802e-01  6.759661e-01  6.532841e-01  6.438687e-01  6.651243e-01   
max    4.609561e+00  4.459457e+00  4.178786e+00  4.147689e+00  4.554145e+00   

          feature_6     feature_7     feature_8     feature_9    feature_10  \
count  2.804000e+04  2.804000e+04  2.804000e+04  2.804000e+04  2.804000e+04   
mean   1.723142e-17 -1.824503e-17  2.027226e-17 -3.649007e-17 -1.216336e-17   
std    1.000018e+00  1.000018e+00  1.000018e+00  1.000018e+00  1.000018e+00   
min   -4.372318e+00 -4.393226e+00 -4.358788e+00 -4.130833e+00 -3.709458e+00   
25%   -6.847500e-01 -6.593376e-01 -6.434965e-01 -6.843001e-01 -6.816693e-01   
50%    1.154686e-02  8.282356e-03  9.997196e-03  1.258585e-03  1.127225e-02   
75%    6.822295e-01  6.558357e-01  6.809009e-01  6.777973e-01  6.982300e-01   
max    3.952793e+00  4.233138e+00  3.871962e+00  3.968831e+00  3.533273e+00   

       ...   feature_247   feature_248   feature_249   feature_250  \
count  ...  2.804000e+04  2.804000e+04  2.804000e+04  2.804000e+04   
mean   ... -3.649007e-17 -3.142200e-17 -8.108904e-18 -2.838116e-17   
std    ...  1.000018e+00  1.000018e+00  1.000018e+00  1.000018e+00   
min    ... -4.083476e+00 -3.974536e+00 -4.290325e+00 -4.144754e+00   
25%    ... -6.984083e-01 -6.724657e-01 -6.347630e-01 -6.801425e-01   
50%    ... -4.124955e-02  2.545302e-02  4.676999e-02  2.809551e-03   
75%    ...  6.674015e-01  6.874343e-01  6.727677e-01  6.936366e-01   
max    ...  3.914447e+00  4.012018e+00  3.559266e+00  3.884945e+00   

        feature_251   feature_252   feature_253   feature_254   feature_255  \
count  28040.000000  2.804000e+04  2.804000e+04  2.804000e+04  2.804000e+04   
mean       0.000000 -1.216336e-17  8.108904e-18  4.054452e-18 -4.865343e-17   
std        1.000018  1.000018e+00  1.000018e+00  1.000018e+00  1.000018e+00   
min       -3.707983 -3.432118e+00 -5.191176e+00 -3.886532e+00 -4.368208e+00   
25%       -0.670488 -7.247984e-01 -6.214652e-01 -6.335267e-01 -6.770794e-01   
50%        0.009433 -1.037732e-03  6.004779e-02  2.774801e-02 -4.657139e-02   
75%        0.679585  7.118310e-01  6.794600e-01  6.547499e-01  6.421796e-01   
max        3.980385  3.551153e+00  3.642976e+00  4.191215e+00  4.697509e+00   

        feature_256  
count  2.804000e+04  
mean  -1.216336e-17  
std    1.000018e+00  
min   -3.600470e+00  
25%   -6.763286e-01  
50%   -7.161695e-02  
75%    6.095615e-01  
max    3.936653e+00  

[8 rows x 256 columns]

### Now lets check the accuracy of prediction before feature engineering for label 2. Then let's predict the test dataset label value before feature engineering.

**Label 2 - Speaker Age**

The value for label 2 (Speaker Age) for the test dataset is predicted as follows.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# Create a KNN model with k=5
k = 5
model = KNeighborsClassifier(n_neighbors=k)
model.fit(X_train, Y_train)
y_pred = model.predict(X_valid)

conf_matrix = metrics.confusion_matrix(Y_valid, y_pred)
accuracy = metrics.accuracy_score(Y_valid, y_pred)
precision = metrics.precision_score(Y_valid, y_pred, average='weighted')
recall = metrics.recall_score(Y_valid, y_pred, average='weighted')

print("Confusion Matrix:\n", conf_matrix)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

Confusion Matrix:
 [[ 36   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  70   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0]
 [  0   1  44   0   0   0   0   0   0   0   0   1   0   0   0   0   0]
 [  0   0   0  78   0   0   0   0   0   0   0   0   0   0   1   0   0]
 [  0   0   0   0 115   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  81   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  46   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  45   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1   0   1   0  46   0   0   0   0   0   0   0   0]
 [  0   0   1   0   0   0   0   0   0  64   0   0   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0   0   0  10   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  30   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0  10   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  11 

In [ ]:
test_pred_before = model.predict(X_test)
df = pd.DataFrame(test_pred_before, columns=['label_2'])
print(df)
df.to_csv('predicted_label_2_before_feature_engineering.csv', index=False)

     label_2
0       26.0
1       31.0
2       25.0
3       27.0
4       31.0
..       ...
745     29.0
746     29.0
747     29.0
748     26.0
749     29.0

[750 rows x 1 columns]


### Feature Engineering

PCA

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components= 0.92, svd_solver= 'full')
pca.fit(X_train)
X_train_after_pca = pd.DataFrame(pca.transform(X_train))
X_valid_after_pca = pd.DataFrame(pca.transform(X_valid))
X_test_after_pca = pd.DataFrame(pca.transform(X_test))
print(X_train_after_pca.shape)

(28040, 55)


In [ ]:
k = 5
model_after_pca = KNeighborsClassifier(n_neighbors=k)
model_after_pca.fit(X_train_after_pca, Y_train)
y_pred_after_pca = model_after_pca.predict(X_valid_after_pca)
print(metrics.confusion_matrix(Y_valid,y_pred_after_pca))
print(metrics.accuracy_score(Y_valid,y_pred_after_pca))
print(metrics.precision_score(Y_valid,y_pred_after_pca, average = 'weighted'))
print(metrics.recall_score(Y_valid,y_pred_after_pca, average = 'weighted'))

[[ 35   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  70   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0]
 [  0   1  44   0   0   0   0   0   0   0   0   1   0   0   0   0   0]
 [  0   0   0  78   0   0   0   0   0   0   0   0   0   0   1   0   0]
 [  0   0   0   0 115   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  81   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  46   0   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0  44   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1   0   1   0  46   0   0   0   0   0   0   0   0]
 [  0   0   1   0   0   0   0   0   0  64   0   0   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0   0   0  10   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  30   0   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0   0   0   0  10   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  11   0   0   0]
 [  0 

Test data is predicted here

In [ ]:
test_pred_after_pca = model_after_pca.predict(X_test_after_pca)
df_after = pd.DataFrame(test_pred_after_pca, columns=['label_1'])
print(df_after)
df_after.to_csv('predicted_label_2_after_feature_engineering.csv', index=False)

     label_1
0       26.0
1       31.0
2       31.0
3       27.0
4       31.0
..       ...
745     29.0
746     29.0
747     29.0
748     29.0
749     29.0

[750 rows x 1 columns]


Getting the csv files after feature engineering

In [ ]:
X_test_df_after = pd.DataFrame(X_test_after_pca)
print(X_test_df_after)
X_test_df_after.to_csv('new_features_label_2.csv', index=False)

            0         1         2         3         4         5         6   \
0    -1.812223  6.687155 -3.641918 -0.345455 -6.543906 -0.232424  3.680529   
1    -6.429202  8.208834 -0.228147  8.026291 -6.485308  4.389094 -1.675062   
2    -4.636527  3.081759 -0.201630  4.513831 -3.444809 -0.378538 -0.598476   
3    -2.033135  5.574049 -0.977140  0.732895  2.986661  4.048778  0.064816   
4     0.862663  5.753936  1.644088  2.243056 -3.438429 -0.409911  1.583930   
..         ...       ...       ...       ...       ...       ...       ...   
745   0.360570 -1.163712 -7.591460 -3.745187  0.835296 -3.999250  0.172361   
746  11.280892  4.073197 -1.448970  0.817718 -0.503205  1.100938  1.003412   
747  -5.626380  2.490690 -2.121079  1.608584  1.840681  5.126356 -5.112083   
748  -4.316032  4.074404  3.652871 -3.176340 -1.589527 -0.223606 -0.181320   
749   3.207397  2.822326 -3.906999 -2.943911 -6.126626 -1.629949 -1.615529   

           7         8         9   ...        45        46     